### ISSUE TITLE
QUESTION: URLs

### ISSUE THREAD

**Issue by berot3** [rj-vinodh/IFTTT-Chrome-Buttons#2]
hi! thanks for this great extension.

Is it possible to also hand over the url of the current site so I can add it to Pocket/Instappaer/iOS readinglist and so on?

**Comment by rj-vinodh** [comment]
Hi Berot3,

Thanks for your support, Please find the latest URL below:

https://rj-vinodh.github.io/Hash-Button-for-IFTTT/

Thanks,
rj-vinodh
